import './domains/authApi'
import './domains/filesApi'
import './domains/machineApi'
import './domains/roomApi'
import './domains/sessionApi'
import './domains/systemApi'
import './domains/templateApi'

export { ApiClient, ApiError, type ApiClientOptions } from './core'
export type { TemplatesResponse } from '@agentchat/protocol/contracts/templates'
